replicaCount: 2

namespace: website-klinik

image:
  repository: riqimaruq/website-klinik
  tag: "4"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: []
